cdk-deploy:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.dylanwilson.dev
  image: node:18.18.0-alpine
  stage: deploy
  script:
    - apk --no-cache add curl zip aws-cli
    - export AWS_DEFAULT_REGION=eu-west-1
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - npm install --progress=false
    - npm run build
    - npm run cdk bootstrap
    - npm run cdk deploy
